-- =============================================================================
-- Check CX 数据库结构
-- AI 模型健康监控面板的完整数据库 Schema
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 枚举类型
-- -----------------------------------------------------------------------------

CREATE TYPE public.provider_type AS ENUM ('openai', 'openai_chat', 'gemini', 'anthropic');

-- -----------------------------------------------------------------------------
-- 2. 表结构
-- -----------------------------------------------------------------------------

-- 配置表：存储 AI 服务商的 API 配置
CREATE TABLE public.check_configs (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name            text NOT NULL,
    type            public.provider_type NOT NULL,
    model           text NOT NULL,
    endpoint        text NOT NULL,
    api_key         text NOT NULL,
    enabled         boolean DEFAULT true,
    is_maintenance  boolean DEFAULT false,
    request_header  jsonb,
    group_name      text,
    metadata        jsonb,
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now()
);

COMMENT ON TABLE public.check_configs IS 'AI 服务商配置表';
COMMENT ON COLUMN public.check_configs.id IS '配置 UUID';
COMMENT ON COLUMN public.check_configs.name IS '配置显示名称';
COMMENT ON COLUMN public.check_configs.type IS '提供商类型: openai, openai_chat, gemini, anthropic';
COMMENT ON COLUMN public.check_configs.model IS '模型名称，如 gpt-4o-mini';
COMMENT ON COLUMN public.check_configs.endpoint IS 'API 端点 URL';
COMMENT ON COLUMN public.check_configs.api_key IS 'API 密钥';
COMMENT ON COLUMN public.check_configs.enabled IS '是否启用检测';
COMMENT ON COLUMN public.check_configs.is_maintenance IS '维护模式，true 时停止检查';
COMMENT ON COLUMN public.check_configs.request_header IS '自定义请求头 (JSONB)';
COMMENT ON COLUMN public.check_configs.group_name IS '分组名称，用于 Dashboard 分组展示';
COMMENT ON COLUMN public.check_configs.metadata IS '自定义请求参数，合并到请求体 (JSONB)';
COMMENT ON COLUMN public.check_configs.created_at IS '创建时间';
COMMENT ON COLUMN public.check_configs.updated_at IS '更新时间';

-- 历史记录表：存储健康检测结果
CREATE TABLE public.check_history (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id       uuid NOT NULL REFERENCES public.check_configs(id) ON DELETE CASCADE,
    status          text NOT NULL,
    latency_ms      integer,
    ping_latency_ms double precision,
    checked_at      timestamptz NOT NULL,
    message         text,
    created_at      timestamptz DEFAULT now(),

    CONSTRAINT check_status_valid CHECK (status IN ('operational', 'degraded', 'failed', 'validation_failed', 'error')),
    CONSTRAINT check_latency_positive CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

COMMENT ON TABLE public.check_history IS '健康检测历史记录表';
COMMENT ON COLUMN public.check_history.id IS '记录 ID';
COMMENT ON COLUMN public.check_history.config_id IS '关联的配置 ID';
COMMENT ON COLUMN public.check_history.status IS '状态: operational, degraded, failed, validation_failed, error';
COMMENT ON COLUMN public.check_history.latency_ms IS '响应延迟 (毫秒)';
COMMENT ON COLUMN public.check_history.ping_latency_ms IS 'Ping 延迟 (毫秒)';
COMMENT ON COLUMN public.check_history.checked_at IS '检测时间';
COMMENT ON COLUMN public.check_history.message IS '状态消息或错误信息';
COMMENT ON COLUMN public.check_history.created_at IS '记录创建时间';

-- 分组信息表：存储分组的额外信息
CREATE TABLE public.group_info (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_name  text NOT NULL UNIQUE,
    website_url text,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);

COMMENT ON TABLE public.group_info IS '分组信息表';
COMMENT ON COLUMN public.group_info.group_name IS '分组名称，关联 check_configs.group_name';
COMMENT ON COLUMN public.group_info.website_url IS '网站地址';

-- 系统通知表：存储全局系统通知
CREATE TABLE public.system_notifications (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    message     text NOT NULL,
    is_active   boolean DEFAULT true,
    level       text DEFAULT 'info',
    created_at  timestamptz DEFAULT now()
);

COMMENT ON TABLE public.system_notifications IS '系统通知表';
COMMENT ON COLUMN public.system_notifications.id IS '通知 UUID';
COMMENT ON COLUMN public.system_notifications.message IS '通知内容，支持 Markdown';
COMMENT ON COLUMN public.system_notifications.is_active IS '是否激活，true 为显示';
COMMENT ON COLUMN public.system_notifications.level IS '通知级别：info, warning, error';
COMMENT ON COLUMN public.system_notifications.created_at IS '创建时间';

-- -----------------------------------------------------------------------------
-- 3. 索引
-- -----------------------------------------------------------------------------

CREATE INDEX idx_check_history_config_id ON public.check_history (config_id);
CREATE INDEX idx_check_history_checked_at ON public.check_history (checked_at DESC);

-- -----------------------------------------------------------------------------
-- 4. 触发器函数
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- 5. 触发器
-- -----------------------------------------------------------------------------

CREATE TRIGGER update_check_configs_updated_at
    BEFORE UPDATE ON public.check_configs
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_group_info_updated_at
    BEFORE UPDATE ON public.group_info
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 6. RLS (Row Level Security)
-- -----------------------------------------------------------------------------

ALTER TABLE public.check_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_notifications ENABLE ROW LEVEL SECURITY;

-- check_history: 允许匿名用户读取
CREATE POLICY allow_anon_select_history
    ON public.check_history
    FOR SELECT
    TO anon
    USING (true);

-- group_info: 允许所有人读取
CREATE POLICY allow_public_read_group_info
    ON public.group_info
    FOR SELECT
    TO public
    USING (true);

-- system_notifications: 允许所有人读取
CREATE POLICY allow_public_read_notifications
    ON public.system_notifications
    FOR SELECT
    TO public
    USING (true);

-- -----------------------------------------------------------------------------
-- 7. 存储过程 / 函数
-- -----------------------------------------------------------------------------

-- 获取最近的检测历史记录
CREATE OR REPLACE FUNCTION public.get_recent_check_history(
    limit_per_config integer DEFAULT 60,
    target_config_ids uuid[] DEFAULT NULL
)
RETURNS TABLE (
    config_id       uuid,
    status          text,
    latency_ms      integer,
    ping_latency_ms integer,
    checked_at      timestamptz,
    message         text,
    name            text,
    type            text,
    model           text,
    endpoint        text,
    group_name      text
)
LANGUAGE sql
STABLE
AS $$
    WITH ranked AS (
        SELECT
            h.id AS history_id,
            h.config_id,
            h.status,
            h.latency_ms,
            h.ping_latency_ms,
            h.checked_at,
            h.message,
            row_number() OVER (PARTITION BY h.config_id ORDER BY h.checked_at DESC) AS rn
        FROM check_history h
        WHERE target_config_ids IS NULL OR h.config_id = ANY(target_config_ids)
    )
    SELECT
        r.config_id,
        r.status,
        r.latency_ms,
        r.ping_latency_ms::integer,
        r.checked_at,
        r.message,
        c.name,
        c.type::text,
        c.model,
        c.endpoint,
        c.group_name
    FROM ranked r
    JOIN check_configs c ON c.id = r.config_id
    WHERE r.rn <= limit_per_config
    ORDER BY c.name ASC, r.checked_at DESC;
$$;

-- 清理过期的历史记录
CREATE OR REPLACE FUNCTION public.prune_check_history(
    limit_per_config integer DEFAULT 60
)
RETURNS void
LANGUAGE sql
VOLATILE
AS $$
    WITH ranked AS (
        SELECT
            id,
            row_number() OVER (PARTITION BY config_id ORDER BY checked_at DESC) AS rn
        FROM check_history
    )
    DELETE FROM check_history
    WHERE id IN (
        SELECT id FROM ranked WHERE rn > limit_per_config
    );
$$;
